# Generated by Django 2.2.25 on 2021-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('lead', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('time', models.DateTimeField()),
                ('time_txt', models.CharField(max_length=100)),
            ],
        ),
    ]
